[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --show-logs"

[test]
startup_wait = 10000

[test.validator]
# Use different ports to avoid conflicts
rpc_port = 8899
websocket_port = 8900
log = "debug"

[features]
seeds = false
skip-lint = false

[programs.localnet]
proof_of_wasted_work = "EDC6ToM56SBkbwgtFK9erEsc7pPoBLWTp7tjrSPtp5DF"

[programs.devnet]
proof_of_wasted_work = "DDn6TMfQaQNGTqik6gfocZYvrwgcQmQoQh5FMu7SSF92"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/dransy/.config/solana/id.json"

[toolchain]
anchor_version = "0.28.0"
